import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

export interface StoredMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

@Entity('conversations')
export class ConversationEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  telegramId: string;

  /**
   * Rolling window of recent messages persisted to DB.
   * Full session history lives in Redis; this is the fallback / long-term record.
   */
  @Column({ type: 'jsonb', default: [] })
  messages: StoredMessage[];

  /** Condensed summary generated by AI to compress older context */
  @Column({ type: 'text', nullable: true })
  summary: string;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
